apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "argocd"
  namespace: "argocd"
spec:
  destination:
    namespace: "argocd"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    chart: "argo-cd"
    helm:
      values: |
        configs:
          cm:
            url: https://argocd.{{ .Values.global.domain_name }}
            oidc.config: |
              name: Keycloak
              issuer: {{ .Values.global.oidc_url }}/realms/default
              clientID: argocd_alfheimr
              clientSecret: $oidc.keycloak.clientSecret
              requestedScopes: [openid, profile, email, roles]
          rbac:
            policy.csv: |
              g, admin, role:admin
            scopes: "[roles]"
        dex:
          enabled: false
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: https
              cert-manager.io/cluster-issuer: letsencrypt-prod
              external-dns.alpha.kubernetes.io/hostname: argocd.{{ .Values.global.domain_name }}
            hosts:
              - argocd.{{ .Values.global.domain_name }}
            tls:
              - secretName: argocd-{{ .Values.global.domain_name }}-cert
                hosts:
                  - argocd.{{ .Values.global.domain_name }}
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: "5.51.2"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"
      - "Replace=true"