apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "ceph-csi-cephfs"
  namespace: "argocd"
spec:
  destination:
    namespace: "ceph-csi-cephfs"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    chart: "ceph-csi-cephfs"
    helm:
      values: |
        provisioner:
          replicaCount: 1
        readAffinity:
          enabled: true
        storageClass:
          create: true
          name: csi-cephfs-ssd
          clusterID: c48dde4f-49ee-43fd-af6f-80c4fe99aa1d
          fsName: mordor
        csiConfig:
          - clusterID: "c48dde4f-49ee-43fd-af6f-80c4fe99aa1d"
            monitors:
              - "pve.infra.arleskog.se"
    repoURL: "https://ceph.github.io/csi-charts"
    targetRevision: "3.10.2"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"