apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "cert-manager"
  namespace: "argocd"
spec:
  destination:
    namespace: "cert-manager"
    server: "https://kubernetes.default.svc"
  project: "default"
  source: null
  sources:
    - chart: "cert-manager"
      helm:
        values: |
          installCRDs: true
          prometheus:
            servicemonitor:
              enabled: true
      repoURL: "https://charts.jetstack.io"
      targetRevision: "1.13.3"
    - chart: "cert-manager-csi-driver"
      repoURL: "https://charts.jetstack.io"
      targetRevision: "0.5.0"
    - path: "environments/mordor/cert-manager"
      repoURL: "https://github.com/albertarleskog/clusters.git"
      targetRevision: "HEAD"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"