apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "ingress-nginx"
  namespace: "argocd"
spec:
  destination:
    namespace: "ingress-nginx"
    server: "https://kubernetes.default.svc"
  project: "default"
  source: null
  sources:
    - chart: "ingress-nginx"
      helm:
        values: |
          controller:
            extraArgs:
              tcp-services-configmap: ingress-nginx/tcp-services
            allowSnippetAnnotations: true
            service:
              ipFamilies:
                - IPv6
            ingressClassResource:
              default: true
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
            config:
              enable-real-ip: true
              proxy-buffer-size: 16k
              proxy-buffers-number: 8
      repoURL: "https://kubernetes.github.io/ingress-nginx"
      targetRevision: "4.9.1"
    - path: "environments/mordor/ingress-nginx"
      repoURL: "https://github.com/albertarleskog/clusters.git"
      targetRevision: "HEAD"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"