apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "kafka"
  namespace: "argocd"
spec:
  destination:
    namespace: "kafka"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    chart: "kafka"
    helm:
      values: |
        controller:
          resourcesPreset: small
          pdb:
            create: true
          persistence:
            size: 8Gi
            storageClass: csi-cephfs-ssd
        metrics:
          jmx:
            enabled: true
            resourcesPreset: nano
          serviceMonitor:
            enabled: true
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "27.1.2"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"