apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "kube-prometheus-stack"
  namespace: "argocd"
spec:
  destination:
    namespace: "kube-prometheus-stack"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    chart: "kube-prometheus-stack"
    helm:
      values: |
        alertmanager:
          enabled: false
        kubeProxy:
          enabled: false
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "57.0.1"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"
      - "Replace=true"