apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "minio"
  namespace: "argocd"
spec:
  destination:
    namespace: "minio"
    server: "https://kubernetes.default.svc"
  project: "default"
  source: null
  sources:
    - chart: "tenant"
      helm:
        values: |
          secrets:
            existingSecret: placeholder
          tenant:
            configuration:
              name: myminio-tenant-env-config
            pools:
              - servers: 1
                volumesPerServer: 3
                size: 3Ti
                storageClassName: local-minio
            metrics:
              enabled: true
            prometheusOperator: true
          ingress:
            api:
              enabled: true
              ingressClassName: nginx
              host: s3.arleskog.se
              annotations:
                nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                nginx.ingress.kubernetes.io/rewrite-target: /
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
                nginx.ingress.kubernetes.io/server-snippet: |
                  client_max_body_size 0;
                nginx.ingress.kubernetes.io/configuration-snippet: |
                  chunked_transfer_encoding off;
              tls:
                - hosts:
                  - s3.arleskog.se
                  secretName: s3-arleskog-se
            console:
              enabled: true
              ingressClassName: nginx
              host: console.s3.arleskog.se
              annotations:
                nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                nginx.ingress.kubernetes.io/rewrite-target: /
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
                nginx.ingress.kubernetes.io/server-snippet: |
                  client_max_body_size 0;
                nginx.ingress.kubernetes.io/configuration-snippet: |
                  chunked_transfer_encoding off;
              tls:
                - hosts:
                  - console.s3.arleskog.se
                  secretName: console-s3-arleskog-se
      repoURL: "https://operator.min.io"
      targetRevision: "5.0.13"
    - path: "environments/mordor/minio"
      repoURL: "https://github.com/albertarleskog/clusters.git"
      targetRevision: "HEAD"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"