apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "postgresql"
  namespace: "argocd"
spec:
  destination:
    namespace: "db"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    chart: "postgresql"
    helm:
      values: |
        primary:
          persistence:
            size: 4Gi
            storageClass: longhorn
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "12.5.5"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"