apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "longhorn"
  namespace: "argocd"
spec:
  destination:
    namespace: "longhorn-system"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    chart: "longhorn"
    helm:
      values: |
        persistence:
          defaultDataLocality: best-effort
          reclaimPolicy: Retain
        defaultSettings:
          backupTarget: "s3://0de979bf-e7f8-43f9-bd7b-d6a697483c6d@s3.eu-central-003.backblazeb2.com/"
          backupTargetCredentialSecret: backblaze
          backupstorePollInterval: 0
          replicaSoftAntiAffinity: true
          replicaAutoBalance: best-effort
          defaultDataLocality: best-effort
          orphanAutoDeletion: true
          snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: true
          guaranteedInstanceManagerCPU: 6
          concurrentAutomaticEngineUpgradePerNodeLimit: 1
    repoURL: "https://charts.longhorn.io"
    targetRevision: "1.5.4"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"