apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
  name: "vault"
  namespace: "argocd"
spec:
  destination:
    namespace: "vault"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    chart: "vault"
    helm:
      values: |
        server:
          ha:
            replicas: 1
            enabled: true
            raft:
              enabled: true
          ingress:
            ingressClassName: nginx
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              external-dns.alpha.kubernetes.io/hostname: vault.{{ .Values.global.domain_name }}
            hosts:
              - host: vault.{{ .Values.global.domain_name }}
            tls:
              - secretName: vault-{{ .Values.global.domain_name | replace "." "-" }}-cert
                hosts:
                  - vault.{{ .Values.global.domain_name }}
          dataStorage:
            size: 256Mi
            storageClass: longhorn
        ui:
          enabled: true
        csi:
          enabled: true
    repoURL: "https://helm.releases.hashicorp.com"
    targetRevision: "0.27.0"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - "CreateNamespace=true"